FROM node:latest

RUN apt-get -y update &&\
    apt-get -y upgrade &&\
    apt-get install build-essential yarn python make g++ -y &&\
    yarn global add truffle 

RUN mkdir -p /app
ADD . /app
WORKDIR /app

RUN yarn install --prod=false  
